### ISSUE TITLE
Missing required package B2 SDK PHP

### ISSUE THREAD

**Issue by owldesign** [gliterd/laravel-backblaze-b2#11]
I kept having an error thrown inside `BackblazeB2ServiceProvider.php` file. 

`Client` class not found, after digging around I had to install `https://github.com/cwhite92/b2-sdk-php` package first.

And add `use ChrisWhite\B2\Client;` to `BackblazeB2ServiceProvider.php`

Fresh install of Laravel 5.6

**Comment by mhetreramesh** [comment]
I've updated the Service provider to use right client SDK.

Its hard to test ServiceProvider & which was causing this issue. Please verify if it is working now. You have to do `composer update`.

**Comment by mhetreramesh** [comment]
Marking this issue closed!
