### ISSUE TITLE
Storage::disk('b2')->allDirectories() returns [] but Storage::disk('b2regions')->allFiles() returns a proper list

### ISSUE THREAD

**Issue by tfortier** [gliterd/laravel-backblaze-b2#15]
When calling "allDirectories" on a b2 disk, using the `Storage::disk('b2')->allDirectories();` method, I received an empty array instead of the expected list of directories.

However, when asking for "allFiles" instead, using the `Storage::disk('b2regions')->allFiles();` method, I received an array containing all the files in the bucket with their ful path which was multiple directories down.

It is important to have the allDirectories method working because it's part of what allows a file manager tool (for instance [https://github.com/InfinetyES/Nova-Filemanager](https://github.com/InfinetyES/Nova-Filemanager)) to work properly.

This result was obtained using php 7.1, Apache and MySql running on Ubuntu. Laravel version 5.6.35 and laravel-backblaze-b2 1.1

To reproduce, install laravel-backblaze-b2, configure a disk and using `php artisan tinker` : 

```
use Illuminate\Support\Facades\Storage;
Storage::disk('b2')->allDirectories();
Storage::disk('b2')->allFiles();
```

**Comment by mhetreramesh** [comment]
List directories is not supported by the b2 sdk as of now.
