### ISSUE TITLE
Cant Get Url in laravel

### ISSUE THREAD

**Issue by craigvc** [gliterd/laravel-backblaze-b2#16]
Calling URL in laravel
```Storage::disk('s3')->url($filename)```
returns an error of no url method.
do you have a way to fix this?
Thanks!

**Comment by alexjustesen** [comment]
I just deployed this package and I'm using the Cloudflare CDN to access my files successfully. More here: https://help.backblaze.com/hc/en-us/articles/217666928-Using-Backblaze-B2-with-the-Cloudflare-CDN
