### ISSUE TITLE
cant list files without preg match issue

### ISSUE THREAD

**Issue by mooseh** [gliterd/laravel-backblaze-b2#18]
so basically im receiving this error when simply looking in a directory with ->files and ->allFiles methods, the error is in listContents method and shows as:
In BackblazeAdapter.php line 239:
                                      
preg_match(): Unknown modifier 'a'  

## Detailed description
below is my code:
```
        $dest = "/amp/logs"
        $config['filesystem'] = "b2logs"
        $storage = Storage::disk($config['filesystem']);
        $remote_files = Storage::disk($config['filesystem'])->allFiles("{$dest}");
```
no matter what i try i get the same error i have tried changing dest to be backslashes, escaping the forward slashes, removed from a slash from the start and added to the end it just has none of it.

## environment

PHP 7.1.31
lumen 5.4

**Comment by mooseh** [comment]
so its the forward slashes not being escaped in your other package gliterd/flysystem-backblaze
I found the fix was on line 231
```$regex = '/^'.preg_quote($directory, '/').'\/.*$/';```
and 235
```$regex = '/^'.preg_quote($directory, '/').'\/(?!.*\\/).*$/';```

also another way of going about this which would be way faster is using strpos?
like so, although this would be recursive so would need a catch like count the number of directory seperators?
```
        $fileObjects = array_filter($fileObjects, function ($fileObject) use ($directory, $regex) {
            return ! strpos($fileObject->getName(), $directory); //preg_match($regex, $fileObject->getName());
        });
```

**Comment by jamesburrow23** [comment]
Have you heard anything more on this issue? I'm also experiencing this problem

**Comment by jamesburrow23** [comment]
For anyone else who stumbles across this issue I forked the problem repo to fix the issue as reported by @mooseh 

```jamesburrow23/laravel-backblaze-b2```

**Comment by mhetreramesh** [comment]
This issue belongs to flysystem adapter.
