### ISSUE TITLE
Received error from B2: required field bucketId cannot be null

### ISSUE THREAD

**Issue by viditgoyal3009** [gliterd/laravel-backblaze-b2#19]
The project has the option of setting bucket name which is not working, I even tried giving bucket id but still getting this error

![Screen Shot 2020-05-05 at 10 24 19 am](https://user-images.githubusercontent.com/13598996/81035937-a1553a80-8eba-11ea-9afb-f70a58355d14.png)

**Comment by mreduar** [comment]
Could you say what the problem was? I am also presenting it.

**Comment by nessor** [comment]
> Could you say what the problem was? I am also presenting it.

You simply have to provide the bucketId from the bucket overview in backblaze :)
